### ISSUE TITLE
jquery.csv syntax

### ISSUE THREAD

**Issue by euisungkang** [BlocklabNL/OEHU-IPFS-backend#2]
jquery.csv '$' syntax is undefined in line 139 of index.js. '$' is supposed to be a shortcut to jQuery, and the index.html even imports a jquery library in line 110.

Error:
Uncaught ReferenceError: $ is not defined                 index.js:139

**Comment by jangerritharms** [comment]
Hey guys, I am Jan, working at Blocklab as a full-stack developer. @ilhanu asked me to have a look at this as well. 

I checked the examples in https://github.com/typeiii/jquery-csv, they all include the actual jQuery library as well which might define the `$` symbol. So try to import jQuery like they do [here](https://github.com/typeiii/jquery-csv/blob/master/examples/from-objects.html) for example. 

```html
    <script src="http://code.jquery.com/jquery-3.3.1.slim.js" integrity="sha256-fNXJFIlca05BIO2Y5zh1xrShK3ME+/lYZ0j+ChxX2DA=" crossorigin="anonymous"></script>
```

**Comment by euisungkang** [comment]
Hey Jan, I did what you suggested and I import jQuery and jQuery-csv as so:
`<script src="/node_modules/jquery-csv/src/jquery.csv.js"></script>
<script src="http://code.jquery.com/jquery-3.3.1.slim.js" integrity="sha256-fNXJFIlca05BIO2Y5zh1xrShK3ME+/lYZ0j+ChxX2DA=" crossorigin="anonymous"></script>'

That seemed to do the trick in defining $.csv, but the latter part of $.csv.toObjects() is still returning an undefined. I'm quite sure toObjects() is undefined because I am incorrectly importing the jquery.csv.js library. I've tried three ways of importing the csv library:
1. '<script src="/jquery.csv.js"></script>'    //Syntax in documentation. Returns 404 error
2. '<script src="/node_modules/jquery-csv/src/jquery.csv.js"></script>'   //Directly importing from node_modules
3. '<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-csv/0.8.3/jquery.csv.min.js"></script>'    //Import from online codebase

None seem to fix the error of toObjects() being undefined.

Error: 
Cannot read property 'toObjects' of undefined

**Comment by jangerritharms** [comment]
Have you tried importing jquery before jquery-csv? So,

```
<script src="http://code.jquery.com/jquery-3.3.1.slim.js" integrity="sha256-fNXJFIlca05BIO2Y5zh1xrShK3ME+/lYZ0j+ChxX2DA=" crossorigin="anonymous"></script>
<script src="/node_modules/jquery-csv/src/jquery.csv.js"></script>
```

I think this is just a simple setup issue, no blockchain expertise needed for this, so I am sure with a little bit of tinkering you will figure it out. What usually helps is to start development from a working example like the ones in the jquery-csv repository. Then adjust the example to what you need specifically.

**Comment by euisungkang** [comment]
That did the trick. I didn't even take into consideration that html was cascading.<br>
I'll make sure to keep questions related to blockchain next time, and study the examples when using a new library. Thanks for the fast replies!
